version : '3'
volumes : 
  mysql_data:

services:
  web:
    image: php:7.3-apache-stretch
    ports:
      - 80:80
    volumes: 
      - .:/var/www/html
      - ./apache/conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql

      